.\" Manpage for UntitledTextBuildSystem.
.TH man 1 "29 Jan 2024" "utbs man page"
.SH NAME
utbs \- Simple build system for automatic build.
.SH SYNOPSIS
utbs -p [path] -f [function]
.SH OPTIONS
-f --function - Function in Utbsource file to start.

-p --path - Path to Utbsource file.

-y --yes - Confirming question.

-p --parallel - Parallel process (faster).
.SH EXAMPLES
You can create file named "Utbsource" and check this example:
        this is comment
        name <
            # this is comment number 2
            echo test:
            echo test2:
        >
        example < echo working: echo working2: >
.SH AUTHOR
Operachi
