.\" Manpage for UntitledTextBuildSystem.
.TH man 1 "29 Jan 2024" "utbs man page"
.SH NAME
utbs \- Simple build system for automatic build.
.SH SYNOPSIS
utbs -p [path] -f [function]
.SH OPTIONS
-f --function - Function in Utbsource file to start.
-p --path - Path to Utbsource file.
.SH AUTHOR
Operachi